export interface ErdTableField {
  name: string
  iskey?: boolean
  figure?: string
  color?: string
  type?: string
}

export interface ErdTableNode {
  key: string
  items?: ErdTableField[]
  loc?: string
}

export interface ErdLink {
  from: string
  to: string
  text?: string
}

export interface ValidationIssue {
  type: 'error' | 'warning'
  message: string
  tableKey?: string
}

/**
 * Generates SQL DDL statements from ERD table nodes and relationships.
 */
export function generateSqlFromErd(
  tables: ErdTableNode[],
  links: ErdLink[],
  dialect: 'postgres' | 'mysql' | 'sqlite' = 'postgres'
): string {
  if (!tables || tables.length === 0) {
    return '-- No tables defined in ERD diagram.'
  }

  const lines: string[] = [
    `-- ==========================================================`,
    `-- Database Schema Generated by Personal Diagram Studio`,
    `-- Dialect: ${dialect.toUpperCase()}`,
    `-- Generated at: ${new Date().toISOString()}`,
    `-- ==========================================================`,
    '',
  ]

  // Create Tables
  tables.forEach((table) => {
    const tableName = table.key.trim().toLowerCase()
    lines.push(`CREATE TABLE IF NOT EXISTS "${tableName}" (`)

    const columnDefs: string[] = []
    const pkCols: string[] = []

    if (table.items && table.items.length > 0) {
      table.items.forEach((item) => {
        const colName = item.name.trim().toLowerCase()
        let colType = 'VARCHAR(255)'

        if (colName === 'id' || colName.endsWith('_id')) {
          colType = dialect === 'postgres' ? 'SERIAL' : 'INTEGER'
        } else if (colName.includes('created') || colName.includes('updated') || colName.includes('date')) {
          colType = 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP'
        } else if (colName.includes('price') || colName.includes('amount') || colName.includes('total')) {
          colType = 'DECIMAL(12, 2)'
        } else if (colName.includes('is_') || colName.includes('has_') || colName.startsWith('active')) {
          colType = dialect === 'sqlite' ? 'INTEGER DEFAULT 1' : 'BOOLEAN DEFAULT TRUE'
        } else if (colName.includes('count') || colName.includes('quantity')) {
          colType = 'INTEGER DEFAULT 0'
        }

        if (item.iskey) {
          pkCols.push(`"${colName}"`)
          columnDefs.push(`  "${colName}" ${colType} NOT NULL`)
        } else {
          columnDefs.push(`  "${colName}" ${colType}`)
        }
      })
    } else {
      columnDefs.push('  "id" SERIAL NOT NULL')
      pkCols.push('"id"')
    }

    if (pkCols.length > 0) {
      columnDefs.push(`  PRIMARY KEY (${pkCols.join(', ')})`)
    }

    lines.push(columnDefs.join(',\n'))
    lines.push(');\n')
  })

  // Add Foreign Key Constraints from Links
  if (links && links.length > 0) {
    lines.push('-- Foreign Key Relationships')
    links.forEach((link, idx) => {
      const fromTable = link.from.toLowerCase()
      const toTable = link.to.toLowerCase()
      const fkName = `fk_${fromTable}_${toTable}_${idx + 1}`

      lines.push(
        `ALTER TABLE "${toTable}" ADD CONSTRAINT "${fkName}" FOREIGN KEY ("${fromTable}_id") REFERENCES "${fromTable}" ("id") ON DELETE CASCADE;`
      )
    })
    lines.push('')
  }

  return lines.join('\n')
}

/**
 * Parses simple SQL CREATE TABLE statements into ERD tables and links.
 */
export function parseSqlToErd(sql: string): {
  nodes: ErdTableNode[]
  links: ErdLink[]
} {
  const nodes: ErdTableNode[] = []
  const links: ErdLink[] = []

  // Clean comments and normalize
  const cleanSql = sql
    .replace(/--.*$/gm, '')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .trim()

  const createTableRegex = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?["`]?([a-zA-Z0-9_]+)["`]?\s*\(([\s\S]*?)\);/gi
  let match: RegExpExecArray | null

  while ((match = createTableRegex.exec(cleanSql)) !== null) {
    const tableName = match[1].toUpperCase()
    const body = match[2]

    const items: ErdTableField[] = []
    const rawLines = body.split(',')

    rawLines.forEach((rawCol) => {
      const line = rawCol.trim()
      if (!line) return

      // Ignore table-level constraints for simple column extraction
      if (/^(CONSTRAINT|PRIMARY\s+KEY|FOREIGN\s+KEY|UNIQUE|KEY|INDEX)/i.test(line)) {
        // If PRIMARY KEY (col), mark col as key
        const pkMatch = /PRIMARY\s+KEY\s*\(\s*["`]?([a-zA-Z0-9_]+)["`]?\s*\)/i.exec(line)
        if (pkMatch) {
          const pkTarget = pkMatch[1].toLowerCase()
          const found = items.find((i) => i.name.toLowerCase() === pkTarget)
          if (found) {
            found.iskey = true
            found.figure = 'Decision'
            found.color = '#be123c'
          }
        }
        return
      }

      const colTokens = line.split(/\s+/)
      const rawName = colTokens[0]?.replace(/["`]/g, '')
      if (!rawName) return

      const isPk = /PRIMARY\s+KEY/i.test(line)

      items.push({
        name: rawName.toLowerCase(),
        iskey: isPk,
        figure: isPk ? 'Decision' : 'Cube1',
        color: isPk ? '#be123c' : '#2563eb',
      })
    })

    if (items.length === 0) {
      items.push({ name: 'id', iskey: true, figure: 'Decision', color: '#be123c' })
    }

    nodes.push({
      key: tableName,
      items,
    })
  }

  // Parse Foreign Keys
  const fkRegex = /ALTER\s+TABLE\s+["`]?([a-zA-Z0-9_]+)["`]?\s+ADD\s+CONSTRAINT[\s\S]*?FOREIGN\s+KEY\s*\(\s*["`]?([a-zA-Z0-9_]+)["`]?\s*\)\s*REFERENCES\s+["`]?([a-zA-Z0-9_]+)["`]?/gi
  let fkMatch: RegExpExecArray | null

  while ((fkMatch = fkRegex.exec(cleanSql)) !== null) {
    const targetTable = fkMatch[1].toUpperCase()
    const sourceTable = fkMatch[3].toUpperCase()

    if (nodes.some((n) => n.key === sourceTable) && nodes.some((n) => n.key === targetTable)) {
      links.push({
        from: sourceTable,
        to: targetTable,
        text: '1:N',
      })
    }
  }

  return { nodes, links }
}

/**
 * Validates ERD Schema for missing primary keys, duplicate columns, and orphan tables.
 */
export function validateErdSchema(tables: ErdTableNode[], links: ErdLink[]): ValidationIssue[] {
  const issues: ValidationIssue[] = []

  tables.forEach((table) => {
    // 1. Check Primary Key
    const hasPk = table.items?.some((item) => item.iskey)
    if (!hasPk) {
      issues.push({
        type: 'warning',
        message: `Table "${table.key}" has no Primary Key defined.`,
        tableKey: table.key,
      })
    }

    // 2. Check Duplicate Columns
    const seenCols = new Set<string>()
    table.items?.forEach((item) => {
      const col = item.name.toLowerCase()
      if (seenCols.has(col)) {
        issues.push({
          type: 'error',
          message: `Table "${table.key}" has duplicate column name "${item.name}".`,
          tableKey: table.key,
        })
      }
      seenCols.add(col)
    })

    // 3. Check Orphan Tables
    const hasRelationship = links.some((l) => l.from === table.key || l.to === table.key)
    if (tables.length > 1 && !hasRelationship) {
      issues.push({
        type: 'warning',
        message: `Table "${table.key}" is disconnected (orphan table with no foreign keys).`,
        tableKey: table.key,
      })
    }
  })

  return issues
}
